"""link

Revision ID: 519391df59e0
Revises: ab66d3ebb25e
Create Date: 2022-12-14 10:00:30.747738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519391df59e0'
down_revision = 'ab66d3ebb25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
